services:
  backend:
    image: gredortools/gredor-backend:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    name: quarkus-backend-network
