quarkus:
  # Ladda in konfiguration med secrets
  config:
    locations: file:${GREDOR_SECRETS_CONFIG_PATH}  # Ska vara en yaml-fil
  # Databas
  datasource:
    jdbc:
      url: jdbc:sqlite:${GREDOR_DATABASE_PATH}?busy_timeout=10000
  # Autentisering mot andra API:er
  tls:
    bolagsverket:
      key-store:
        p12:
          path: ${gredor.secrets.cert-bolagsverket.path}  # Ska vara en PKCS#12-fil
          password: ${gredor.secrets.cert-bolagsverket.password}
  rest-client:
    hamtaArsredovisningsinformation_1_4_yaml:
      tls-configuration-name: bolagsverket
    lamnaInArsredovisning_2_1_yaml:
      tls-configuration-name: bolagsverket

gredor:
  rest:
    use-x-real-ip: ${GREDOR_USE_X_REAL_IP}
