# Overrides för utvecklingsmiljö
quarkus:
  http:
    cors:
      origins: /.*/

gredor:
  bolagsverket-api:
    # Går mot Bolagsverkets statiska testmiljö
    hamta-arsredovisningsinformation:
      baseurl: https://api-accept2.bolagsverket.se/testapi/hamta-arsredovisningsinformation/
    lamna-in-arsredovisning:
      baseurl: https://api-accept2.bolagsverket.se/testapi/lamna-in-arsredovisning/
  rest:
    # Avaktivera verifiering av signatur - funkar inte pga att vi får statiskt data från Bolagsverket
    verify-signer: false
