# Overrides för utvecklingsmiljö
quarkus:
  http:
    cors:
      origins: /.*/

gredor:
  auth:
    limit:
      per-interval: 200
      per-interval-and-person: 10
      interval-in-hours: 168
  bankid:
    # BankID är mockat i utvecklingsmiljön
    test-mode: true
  bolagsverket:
    # Bolagsverkets API är mockat i utvecklingsmiljön
    hamta-arsredovisningsinformation:
      baseurl: unused
    lamna-in-arsredovisning:
      baseurl: unused
  rest:
    use-x-real-ip: false
